Music/Music/Models/ViewModels/AlbumViewModel.cs
using DataStructure;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Music.Models.ViewModels
{
    public class AlbumViewModel : ViewModel
    {
        [Required]
        
        public string Name { get; set; }

        [Required]

        public int YearReleased { get; set; }



        // MARK:- Many-to-Many Relationships

        public AlbumViewModel() : base() { }

        public AlbumViewModel(Album album) : base(album)
        {
            Name = album.Name;
            YearReleased = album.YearReleased;
        }

        public static List<AlbumViewModel> ToList(List<Album> albums)
        {
            List<AlbumViewModel> albumViewModels = new List<AlbumViewModel>();
            foreach (Album album in albums)
            {
                AlbumViewModel albumViewModel = new AlbumViewModel(album);
                albumViewModels.Add(albumViewModel);
            }
            return albumViewModels;
        }
    }
}

Music/Music/Controllers/AlbumsController.cs
namespace Music.Controllers
{
    using System.Collections.Generic;
    using System.Net;
    using System.Web.Mvc;
    using DataAccess.Repositories;
    using DataStructure;
    using Music.Models.ViewModels;
    using MvcPaging;

    //[Authorize(Roles = "admin")]
    public class AlbumsController : BaseController<Album>
    {
        public AlbumsController() : base(UnitOfWork.Main.AlbumRepository) { }

        public ActionResult Index(int? page, string queryString)
        {
            List<Album> albums;

            if (queryString != null && queryString != "")
            {
                albums = uow.AlbumRepository.SearchBy(queryString);
            }
            else
            {
                albums = uow.AlbumRepository.GetAll();
            }

            List<AlbumViewModel> albumViewModels = AlbumViewModel.ToList(albums);

            int maxPages = this.CalculatePagesCount(albumViewModels);
            int currentPage = this.CalculateCurrentPageNumber(page, maxPages);

            ViewBag.Page = currentPage;
            ViewBag.Max = maxPages;

            return View(albumViewModels.ToPagedList(currentPage, pageSize));
        }

        //[Authorize(Roles = "admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = uow.AlbumRepository.GetByID((int)id);
            if (album == null)
            {
                return HttpNotFound();
            }
            AlbumViewModel albumViewModel = new AlbumViewModel(album);
            return View(albumViewModel);
        }

        public ActionResult Create()
        {
            return View();
        }

        //[Authorize(Roles = "admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = uow.AlbumRepository.GetByID((int)id);
            if (album == null)
            {
                return HttpNotFound();
            }
            AlbumViewModel albumViewModel = new AlbumViewModel(album);
            return View(albumViewModel);
        }

        //[Authorize(Roles = "admin")]
        // GET: Actors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = uow.AlbumRepository.GetByID((int)id);
            if (album == null)
            {
                return HttpNotFound();
            }
            AlbumViewModel albumViewModel = new AlbumViewModel(album);
            return View(albumViewModel);
        }

        // POST: Directors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,YearReleased,CreatedAt,UpdatedAt")] AlbumViewModel albumViewModel)
        {

            if (ModelState.IsValid)
            {
                Album album = Transform(albumViewModel);
                uow.AlbumRepository.CreateOrUpdate(album);
                return RedirectToAction("Index");
            }

            return View(albumViewModel);
        }

        // POST: Directors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,YearReleased,CreatedAt,UpdatedAt")] AlbumViewModel albumViewModel)
        {
            if (ModelState.IsValid)
            {
                Album album = Transform(albumViewModel);
                uow.AlbumRepository.CreateOrUpdate(album);
                return RedirectToAction("Index");
            }
            return View(albumViewModel);
        }

        private Album Transform(AlbumViewModel albumViewModel)
        {
            return new Album()
            {
                ID = albumViewModel.ID,
                Name = albumViewModel.Name,
                YearReleased = albumViewModel.YearReleased,
                CreatedAt = albumViewModel.CreatedAt,
                UpdatedAt = albumViewModel.UpdatedAt
            };
        }

    }
}

Music/Music/Views/Albums/Create.cshtml
@model Music.Models.ViewModels.AlbumViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Album</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.YearReleased, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.YearReleased, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.YearReleased, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Music/Music/Views/Albums/Delete.cshtml
@model  Music.Models.ViewModels.AlbumViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Album</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.YearReleased)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.YearReleased)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedAt)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Music/Music/Views/Albums/Details.cshtml
@model  Music.Models.ViewModels.AlbumViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Album</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.YearReleased)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.YearReleased)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedAt)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Music/Music/Views/Albums/Edit.cshtml
@model Music.Models.ViewModels.AlbumViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Album</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.YearReleased, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.YearReleased, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.YearReleased, "", new { @class = "text-danger" })
            </div>
        </div>

      

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Music/Music/Views/Albums/Index.cshtml
@model IPagedList<Music.Models.ViewModels.AlbumViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Albums Index</h2>

<div class="panel-heading d-flex justify-content-start">
    @using (Html.BeginForm())
    {
        <p>@Html.TextBox("queryString", null, htmlAttributes: new { @class = "form-control", placeholder = "Search" })</p>
        <input type="submit" value="Filter" class="hidden" />
    }
</div>

@if (User.IsInRole("admin"))
{
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
}
<table class="table" style="border:2px dotted black">
    <tr>
        <th>
            Name
        </th>
        <th>
            YearReleased
        </th>
        @if (User.IsInRole("admin"))
        {
            <th>
                CreatedAt
            </th>
            <th>
                UpdatedAt
            </th>
            <th>Actions</th>
        }

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.YearReleased)
            </td>
            @if (User.IsInRole("admin"))
            {
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedAt)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UpdatedAt)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                </td>
            }

        </tr>
    }

</table>
<div class="btn-group" role="group" aria-label="...">
    @if (ViewBag.Page > 0)
    {
        <a href="@Url.Action("Index", "Albums", new { page = ViewBag.Page - 1 })" style="float:left;text-decoration: none; display: inline-block; padding: 7px 9px;border:1px solid gray; border-radius:8px;
  color: black;">←</a>
    }
    @if (ViewBag.Page != ViewBag.Max && ViewBag.Max > 0)
    {
        <a href="@Url.Action("Index", "Albums", new { page = ViewBag.Page + 1 })" style="text-decoration: none; display: inline-block; padding: 7px 9px;border:1px solid gray; border-radius:8px;
  color: black;">→</a>
    }
</div>