Music/Music/Models/ViewModels/StyleViewModel.cs
namespace Music.Models.ViewModels
{
    using DataStructure;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class StyleViewModel : ViewModel
    {
        [Required]
        public string Title { get; set; }

        public StyleViewModel() : base() { }

        public StyleViewModel(Style style) : base(style)
        {
            Title = style.Title;
        }

        public static List<StyleViewModel> ToList(List<Style> styles)
        {
            List<StyleViewModel> styleViewModels = new List<StyleViewModel>();
            foreach (Style style in styles)
            {
                StyleViewModel styleViewModel = new StyleViewModel(style);
                styleViewModels.Add(styleViewModel);
            }
            return styleViewModels;
        }
    }
}

Music/Music/Controllers/StylesController.cs
namespace Music.Controllers
{
    using System.Collections.Generic;
    using System.Net;
    using System.Web.Mvc;
    using DataAccess.Repositories;
    using DataStructure;
    using Music.Models.ViewModels;
    using MvcPaging;

    //[Authorize(Roles = "admin")]
    public class StylesController : BaseController<Style>
    {
        public StylesController() : base(UnitOfWork.Main.StyleRepository) { }

        public ActionResult Index(int? page, string queryString)
        {
            List<Style> styles;

            if (queryString != null && queryString != "")
            {
                styles = uow.StyleRepository.SearchBy(queryString);
            }
            else
            {
                styles = uow.StyleRepository.GetAll();
            }

            List<StyleViewModel> styleViewModels = StyleViewModel.ToList(styles);

            int maxPages = this.CalculatePagesCount(styleViewModels);
            int currentPage = this.CalculateCurrentPageNumber(page, maxPages);

            ViewBag.Page = currentPage;
            ViewBag.Max = maxPages;

            return View(styleViewModels.ToPagedList(currentPage, pageSize));
        }

        //[Authorize(Roles = "admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Style style = uow.StyleRepository.GetByID((int)id);
            if (style == null)
            {
                return HttpNotFound();
            }
            StyleViewModel styleViewModel = new StyleViewModel(style);
            return View(styleViewModel);
        }

        public ActionResult Create()
        {
            return View();
        }

        //[Authorize(Roles = "admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Style style = uow.StyleRepository.GetByID((int)id);
            if (style == null)
            {
                return HttpNotFound();
            }
            StyleViewModel styleViewModel = new StyleViewModel(style);
            return View(styleViewModel);
        }

        //[Authorize(Roles = "admin")]
        // GET: Actors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Style style = uow.StyleRepository.GetByID((int)id);
            if (style == null)
            {
                return HttpNotFound();
            }
            StyleViewModel styleViewModel = new StyleViewModel(style);
            return View(styleViewModel);
        }

        // POST: Genres/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Title,CreatedAt,UpdatedAt")] StyleViewModel styleViewModel)
        {
            if (ModelState.IsValid)
            {
                Style style = Transform(styleViewModel);
                uow.StyleRepository.CreateOrUpdate(style);
                return RedirectToAction("Index");
            }

            return View(styleViewModel);
        }

        // POST: Genres/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Title,CreatedAt,UpdatedAt")] StyleViewModel styleViewModel)
        {
            if (ModelState.IsValid)
            {
                Style style = Transform(styleViewModel);
                uow.StyleRepository.CreateOrUpdate(style);
                return RedirectToAction("Index");
            }
            return View(styleViewModel);
        }

        private Style Transform(StyleViewModel styleViewModel)
        {
            return new Style()
            {
                ID = styleViewModel.ID,
                Title = styleViewModel.Title,
                CreatedAt = styleViewModel.CreatedAt,
                UpdatedAt = styleViewModel.UpdatedAt
            };
        }

    }
}

Music/Music/Views/Styles/Create.cshtml
@model Music.Models.ViewModels.StyleViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Style</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Music/Music/Views/Styles/Delete.cshtml
@model Music.Models.ViewModels.StyleViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Style</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedAt)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Music/Music/Views/Styles/Details.cshtml
@model Music.Models.ViewModels.StyleViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Style</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedAt)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Music/Music/Views/Styles/Edit.cshtml
@model Music.Models.ViewModels.StyleViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Style</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

       

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Music/Music/Views/Styles/Index.cshtml
@model IEnumerable<Music.Models.ViewModels.StyleViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Styles Index</h2>
<div class="panel-heading d-flex justify-content-start">
    @using (Html.BeginForm())
    {
        <p>@Html.TextBox("queryString", null, htmlAttributes: new { @class = "form-control", placeholder = "Search" })</p>
        <input type="submit" value="Filter" class="hidden" />
    }
</div>

@if (User.IsInRole("admin"))
{
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
}


<table class="table" style="border:2px dotted black">
    <tr>
        <th>
            Title
        </th>
        @if (User.IsInRole("admin"))
        {
            <th>
                CreatedAt
            </th>
            <th>
                UpdatedAt
            </th>
            <th>
                Actions
            </th>
        }
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            @if (User.IsInRole("admin"))
            {
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedAt)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UpdatedAt)
                </td>

                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                </td>
            }
        </tr>
    }
</table>

<div class="btn-group" role="group" aria-label="...">
    @if (ViewBag.Page > 0)
    {
        <a href="@Url.Action("Index", "Styles", new { page = ViewBag.Page - 1 })" style="float:left;text-decoration: none; display: inline-block; padding: 7px 9px;border:1px solid gray; border-radius:8px;
  color: black;">←</a>
    }
    @if (ViewBag.Page < ViewBag.Max && ViewBag.Max > 0)
    {
        <a href="@Url.Action("Index", "Styles", new { page = ViewBag.Page + 1 })" style="text-decoration: none; display: inline-block; padding: 7px 9px;border:1px solid gray; border-radius:8px;
  color: black;">→</a>
    }
</div>