Music/Music/Models/ViewModels/SongViewModel.cs
namespace Music.Models.ViewModels
{
    using DataStructure;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;

    public class SongViewModel : ViewModel
    {
        [Required]
      
        public string Name { get; set; }

        [Required]
        public int Duration { get; set; }

        // MARK: - 1-to-1 Relationships

        public int AlbumID { get; set; }
        public AlbumViewModel Album { get; set; }

        public int StyleID { get; set; }
        public StyleViewModel Style { get; set; }

        // MARK: - Many-to-Many Relationships

        public List<int> ArtistIDs { get; set; }
        public ICollection<ArtistViewModel> Artists { get; set; }

        public SongViewModel() : base() { }

        public SongViewModel(Song song) : base(song)
        {
            Name = song.Name;
            Duration = song.Duration;

            if (song.Album != null)
            {
                AlbumID = song.Album.ID;
                Album = new AlbumViewModel(song.Album);
            }

            if (song.Style != null)
            {
                StyleID = song.Style.ID;
                Style = new StyleViewModel(song.Style);
            }

            if (song.Artists != null)
            {
                ArtistIDs = new List<int>();
                foreach (Artist artist in song.Artists)
                {
                    ArtistIDs.Add(artist.ID);
                }

                Artists = ArtistViewModel.ToList(song.Artists.ToList());
            }
        }

        public static List<SongViewModel> ToList(ICollection<Song> songs)
        {
            List<SongViewModel> songViewModels = new List<SongViewModel>();
            foreach (Song song in songs)
            {
                SongViewModel songViewModel = new SongViewModel(song);
                songViewModels.Add(songViewModel);
            }
            return songViewModels;
        }
    }
}

Music/Music/Controllers/SongsController.cs
namespace Music.Controllers
{
    using System.Collections.Generic;
    using System.Net;
    using System.Web.Mvc;
    using DataAccess.Repositories;
    using DataStructure;
    using Music.Models.ViewModels;
    using MvcPaging;

    public class SongsController : BaseController<Song>
    {
        public SongsController() : base(UnitOfWork.Main.SongRepository) { }

        public ActionResult Index(int? page, string queryString)
        {
            List<Song> songs;
            if (queryString != null && queryString != "")
            {
                songs = uow.SongRepository.SearchBy(queryString);
            }
            else
            {
                songs = uow.SongRepository.GetAll();
            }

            List<SongViewModel> songViewModels = SongViewModel.ToList(songs);

            int maxPages = this.CalculatePagesCount(songViewModels);
            int currentPage = this.CalculateCurrentPageNumber(page, maxPages);

            ViewBag.Page = currentPage;
            ViewBag.Max = maxPages;

            return View(songViewModels.ToPagedList(currentPage, pageSize));
        }

        //[Authorize(Roles = "admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Song song = uow.SongRepository.GetByID((int)id);
            if (song == null)
            {
                return HttpNotFound();
            }
            SongViewModel songViewModel = new SongViewModel(song);
            return View(songViewModel);
        }

        public ActionResult Create()
        {
            List<StyleViewModel> styles = StyleViewModel.ToList(uow.StyleRepository.GetAll());
            ViewBag.Styles = new SelectList(styles, "ID", "Title");

            List<AlbumViewModel> albums = AlbumViewModel.ToList(uow.AlbumRepository.GetAll());
            ViewBag.Albums = new SelectList(albums, "ID", "Name");

            List<ArtistViewModel> artists = ArtistViewModel.ToList(uow.ArtistRepository.GetAll());
            ViewBag.Artists = new MultiSelectList(artists, "ID", "FullName");

            return View();
        }

        //[Authorize(Roles = "admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Song song = uow.SongRepository.GetByID((int)id);
            if (song == null)
            {
                return HttpNotFound();
            }
            SongViewModel songViewModel = new SongViewModel(song);

            List<StyleViewModel> styles = StyleViewModel.ToList(uow.StyleRepository.GetAll());
            ViewBag.Styles = new SelectList(styles, "ID", "Title", songViewModel.StyleID);

            List<AlbumViewModel> albums = AlbumViewModel.ToList(uow.AlbumRepository.GetAll());
            ViewBag.Albums = new SelectList(albums, "ID", "Name", selectedValue: songViewModel.AlbumID);

            List<ArtistViewModel> artists = ArtistViewModel.ToList(uow.ArtistRepository.GetAll());
            ViewBag.Artists = new MultiSelectList(artists, "ID", "FullName", songViewModel.ArtistIDs);

            return View(songViewModel);
        }

        //[Authorize(Roles = "admin")]
        // GET: Actors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Song song = uow.SongRepository.GetByID((int)id);
            if (song == null)
            {
                return HttpNotFound();
            }
            SongViewModel songViewModel = new SongViewModel(song);
            return View(songViewModel);
        }

        // POST: Films/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Duration,StyleID,AlbumID,ArtistIDs,CreatedAt,UpdatedAt")] SongViewModel songViewModel)
        {
            if (ModelState.IsValid)
            {
                Song song = Transform(songViewModel);
                uow.SongRepository.CreateOrUpdate(song);
                return RedirectToAction("Index");
            }

            return View(songViewModel);
        }

        // POST: Films/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Duration,StyleID,AlbumID,ArtistIDs,CreatedAt,UpdatedAt")] SongViewModel songViewModel)
        {
            if (ModelState.IsValid)
            {
                Song song = Transform(songViewModel);
                uow.SongRepository.CreateOrUpdate(song);
                return RedirectToAction("Index");
            }
            return View(songViewModel);
        }

        private Song Transform(SongViewModel songViewModel)
        {
            return new Song()
            {
                ID = songViewModel.ID,
                Name = songViewModel.Name,
                Style = uow.StyleRepository.GetByID(songViewModel.StyleID),
                Album = uow.AlbumRepository.GetByID(songViewModel.AlbumID),
                CreatedAt = songViewModel.CreatedAt,
                UpdatedAt = songViewModel.UpdatedAt,
                Artists = uow.ArtistRepository.GetByIDs(songViewModel.ArtistIDs),
                Duration = songViewModel.Duration
            };
        }

    }
}

Music/Music/Views/Songs/Create.cshtml
@model Music.Models.ViewModels.SongViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Film</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Style, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-5">
            @Html.DropDownListFor(model => model.StyleID, ViewBag.Styles as SelectList, "Select Style", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.StyleID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Album, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-5">
            @Html.DropDownListFor(model => model.AlbumID, ViewBag.Albums as SelectList, "Select Album", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.AlbumID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Artists, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-5">
            @Html.ListBoxFor(x => x.ArtistIDs, ViewBag.Artists as MultiSelectList, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Artists, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Music/Music/Views/Songs/Delete.cshtml
@model Music.Models.ViewModels.SongViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Song</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Duration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Duration)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Style)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Style.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Album)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Album.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Artists)
        </dt>

        @foreach (Music.Models.ViewModels.ArtistViewModel actor in Model.Artists)
        {
            <dd>
                @actor.FullName
            </dd>
        }

        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedAt)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Music/Music/Views/Songs/Details.cshtml
@model Music.Models.ViewModels.SongViewModel


@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Film</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Duration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Duration)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Style)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Style.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Album)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Album.Name)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Artists)
        </dt>

        @foreach (Music.Models.ViewModels.ArtistViewModel actor in Model.Artists)
        {
            <dd>
                @actor.FullName
            </dd>
        }





        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedAt)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Music/Music/Views/Songs/Edit.cshtml
@model Music.Models.ViewModels.SongViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Song</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Style, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.DropDownListFor(model => model.StyleID, ViewBag.Styles as SelectList, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StyleID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Album, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.DropDownListFor(model => model.AlbumID, ViewBag.Albums as SelectList, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AlbumID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Artists, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.ListBoxFor(x => x.ArtistIDs, ViewBag.Artists as MultiSelectList, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Artists, "", new { @class = "text-danger" })
            </div>
        </div>

       

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Music/Music/Views/Songs/Index.cshtml
@model IPagedList<Music.Models.ViewModels.SongViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Songs Index</h2>
<div class="panel-heading d-flex justify-content-start">
    @using (Html.BeginForm())
    {
        <p>@Html.TextBox("queryString", null, htmlAttributes: new { @class = "form-control", placeholder = "Search" })</p>
        <input type="submit" value="Filter" class="hidden" />
    }
</div>
@if (User.IsInRole("admin"))
{
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
}
<table class="table" style="border:2px dotted black">
    <tr>
        <th>
            Name
        </th>
        <th>
            Duration
        </th>
        <th>
            Style
        </th>
        <th>
            Album
        </th>
        @if (User.IsInRole("admin"))
        {
            <th>
                CreatedAt
            </th>
            <th>
                UpdatedAt
            </th>
            <th>Actions</th>
        }


    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Duration) sec.
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Style.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Album.Name)
            </td>
            @if (User.IsInRole("admin"))
            {
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedAt)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UpdatedAt)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                </td>
            }
        </tr>
    }

</table>
<div class="btn-group" role="group" aria-label="...">
    @if (ViewBag.Page > 0)
    {
        <a href="@Url.Action("Index", "Songs", new { page = ViewBag.Page - 1 })" style="float:left;text-decoration: none; display: inline-block; padding: 7px 9px;border:1px solid gray; border-radius:8px;
  color: black;">←</a>
    }
    @if (ViewBag.Page != ViewBag.Max && ViewBag.Max > 0)
    {
        <a href="@Url.Action("Index", "Songs", new { page = ViewBag.Page + 1 })" style="text-decoration: none; display: inline-block; padding: 7px 9px;border:1px solid gray; border-radius:8px;
  color: black;">→</a>
    }
</div>