Music/Music/Models/ViewModels/ArtistViewModel.cs
using DataStructure;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Music.Models.ViewModels
{
    public class ArtistViewModel : ViewModel
    {
        [Required]
        
        public string FirstName { get; set; }

        [Required]
      
        public string LastName { get; set; }

        public string FullName
        {
            get
            {
                return FirstName + " " + LastName;
            }
        }

        // MARK:- Many-to-Many Relationships

        public ArtistViewModel() : base() { }

        public ArtistViewModel(Artist artist) : base(artist)
        {
            FirstName = artist.FirstName;
            LastName = artist.LastName;
        }

        public static List<ArtistViewModel> ToList(List<Artist> artists)
        {
            List<ArtistViewModel> artistViewModels = new List<ArtistViewModel>();
            foreach (Artist artist in artists)
            {
                ArtistViewModel artistViewModel = new ArtistViewModel(artist);
                artistViewModels.Add(artistViewModel);
            }
            return artistViewModels;
        }
    }
}

Music/Music/Controllers/ArtistsController.cs
namespace Music.Controllers
{
    using System.Collections.Generic;
    using System.Net;
    using System.Web.Mvc;
    using DataAccess.Repositories;
    using DataStructure;
    using Music.Models.ViewModels;
    using MvcPaging;

    //[Authorize(Roles = "admin")]
    public class ArtistsController : BaseController<Artist>
    {
        public ArtistsController() : base(UnitOfWork.Main.ArtistRepository) { }

        public ActionResult Index(int? page, string queryString)
        {
            List<Artist> artists;

            if (queryString != null && queryString != "")
            {
                artists = uow.ArtistRepository.SearchBy(queryString);
            }
            else
            {
                artists = uow.ArtistRepository.GetAll();
            }

            List<ArtistViewModel> artistViewModels = ArtistViewModel.ToList(artists);

            int maxPages = this.CalculatePagesCount(artistViewModels);
            int currentPage = this.CalculateCurrentPageNumber(page, maxPages);

            ViewBag.Page = currentPage;
            ViewBag.Max = maxPages;

            return View(artistViewModels.ToPagedList(currentPage, pageSize));
        }

        //[Authorize(Roles = "admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artist artist = uow.ArtistRepository.GetByID((int)id);
            if (artist == null)
            {
                return HttpNotFound();
            }
            ArtistViewModel artistViewModel = new ArtistViewModel(artist);
            return View(artistViewModel);
        }

        public ActionResult Create()
        {
            return View();
        }

        //[Authorize(Roles = "admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artist artist = uow.ArtistRepository.GetByID((int)id);
            if (artist == null)
            {
                return HttpNotFound();
            }
            ArtistViewModel artistViewModel = new ArtistViewModel(artist);
            return View(artistViewModel);
        }

        //[Authorize(Roles = "admin")]
        // GET: Actors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artist artist = uow.ArtistRepository.GetByID((int)id);
            if (artist == null)
            {
                return HttpNotFound();
            }
            ArtistViewModel artistViewModel = new ArtistViewModel(artist);
            return View(artistViewModel);
        }

        // POST: Actors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,FirstName,LastName,CreatedAt,UpdatedAt")] ArtistViewModel artistViewModel)
        {
            if (ModelState.IsValid)
            {
                Artist artist = Transform(artistViewModel);
                uow.ArtistRepository.CreateOrUpdate(artist);
                return RedirectToAction("Index");
            }
            return View(artistViewModel);
        }

        // POST: Actors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,FirstName,LastName,CreatedAt,UpdatedAt")] ArtistViewModel artistViewModel)
        {
            if (ModelState.IsValid)
            {
                Artist artist = Transform(artistViewModel);
                uow.ArtistRepository.CreateOrUpdate(artist);
                return RedirectToAction("Index");
            }
            return View(artistViewModel);
        }

        public Artist Transform(ArtistViewModel artistViewModel)
        {
            return new Artist()
            {
                ID = artistViewModel.ID,
                FirstName = artistViewModel.FirstName,
                LastName = artistViewModel.LastName,
                CreatedAt = artistViewModel.CreatedAt,
                UpdatedAt = artistViewModel.UpdatedAt
            };
        }
    }
}

Music/Music/Views/Artists/Create.cshtml
@model Music.Models.ViewModels.ArtistViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Artist</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Music/Music/Views/Artists/Delete.cshtml
@model Music.Models.ViewModels.ArtistViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Artist</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        

        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedAt)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Music/Music/Views/Artists/Details.cshtml
@model Music.Models.ViewModels.ArtistViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Artist</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

       

        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedAt)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Music/Music/Views/Artists/Edit.cshtml
@model Music.Models.ViewModels.ArtistViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Artist</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

     

       

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Music/Music/Views/Artists/Index.cshtml
@model IEnumerable<Music.Models.ViewModels.ArtistViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Artists Index</h2>
<div class="panel-heading d-flex justify-content-start">
    @using (Html.BeginForm())
    {
        <p>@Html.TextBox("queryString", null, htmlAttributes: new { @class = "form-control", placeholder = "Search" })</p>
        <input type="submit" value="Filter" class="hidden" />
    }
</div>
@if (User.IsInRole("admin"))
{
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
}
    <table class="table" style="border:2px dotted black">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            @if (User.IsInRole("admin"))
            {
                <th>
                    @Html.DisplayNameFor(model => model.CreatedAt)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UpdatedAt)
                </th>
                <th>
                   Actions
                </th>
            }
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                @if (User.IsInRole("admin"))
                {
                    <td>
                        @Html.DisplayFor(modelItem => item.CreatedAt)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UpdatedAt)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                        @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                    </td>
                }
            </tr>
        }

    </table>
    <div class="btn-group" role="group" aria-label="...">
        @if (ViewBag.Page > 0)
        {
            <a href="@Url.Action("Index", "Artists", new { page = ViewBag.Page - 1 })" style="float:left;text-decoration: none; display: inline-block; padding: 7px 9px;border:1px solid gray; border-radius:8px;
  color: black;">←</a>
        }
        @if (ViewBag.Page != ViewBag.Max && ViewBag.Max > 0)
        {
            <a href="@Url.Action("Index", "Artists", new { page = ViewBag.Page + 1 })" style="text-decoration: none; display: inline-block; padding: 7px 9px;border:1px solid gray; border-radius:8px;
  color: black;">→</a>
        }
    </div>